function [params, species] = chromatinInitialize()
% This file is automatically generated by update_model.m from the chromatin_model spreadsheet
% Model URL: chromatin_model.xlsx


% PARAMETERS
params(1,1) = 10; % Widom 2011
params(1,2) = 3; % Hill coefficient for TF binding
params(1,3) = 0.8; % Kd for TF binding
params(2,1) = 75; % Widom 2011
params(3,1) = 12; % Widom 2011
params(3,2) = 3; % Hill coefficient for TF binding
params(3,3) = 0.8; % Kd for TF binding
params(4,1) = 60; % Widom 2011
params(5,1) = 14.4; % Widom 2011
params(5,2) = 3; % Hill coefficient for TF binding
params(5,3) = 0.8; % Kd for TF binding
params(6,1) = 48; % Widom 2011
params(7,1) = 17.28; % Widom 2011
params(7,2) = 3; % Hill coefficient for TF binding
params(7,3) = 0.8; % Kd for TF binding
params(8,1) = 38.4; % Widom 2011
params(9,1) = 20.736; % Widom 2011
params(9,2) = 3; % Hill coefficient for TF binding
params(9,3) = 0.8; % Kd for TF binding
params(10,1) = 30.72; % Widom 2011
params(11,1) = 24.8832; % Widom 2011
params(11,2) = 3; % Hill coefficient for TF binding
params(11,3) = 0.8; % Kd for TF binding
params(12,1) = 24.576; % Widom 2011
params(13,1) = 29.8598; % Widom 2011
params(13,2) = 3; % Hill coefficient for TF binding
params(13,3) = 0.8; % Kd for TF binding
params(14,1) = 19.6608; % Widom 2011
params(15,1) = 35.8318; % Widom 2011
params(15,2) = 3; % Hill coefficient for TF binding
params(15,3) = 0.8; % Kd for TF binding
params(16,1) = 15.7286; % Widom 2011
params(17,1) = 42.9982; % Widom 2011
params(17,2) = 3; % Hill coefficient for TF binding
params(17,3) = 0.8; % Kd for TF binding
params(18,1) = 12.5829; % Widom 2011
params(19,1) = 51.5978; % Widom 2011
params(19,2) = 3; % Hill coefficient for TF binding
params(19,3) = 0.8; % Kd for TF binding
params(20,1) = 10.0663; % Widom 2011
params(21,1) = 61.9174; % Widom 2011
params(21,2) = 3; % Hill coefficient for TF binding
params(21,3) = 0.8; % Kd for TF binding
params(22,1) = 8.05306; % Widom 2011
params(23,1) = 74.3008; % Widom 2011
params(23,2) = 3; % Hill coefficient for TF binding
params(23,3) = 0.8; % Kd for TF binding
params(24,1) = 6.44245; % Widom 2011
params(25,1) = 89.161; % Widom 2011
params(25,2) = 3; % Hill coefficient for TF binding
params(25,3) = 0.8; % Kd for TF binding
params(26,1) = 5.15396; % Widom 2011
params(27,1) = 106.993; % Widom 2011
params(27,2) = 3; % Hill coefficient for TF binding
params(27,3) = 0.8; % Kd for TF binding
params(28,1) = 4.12317; % Widom 2011
params(29,1) = 10; % Widom 2011
params(29,2) = 3; % Hill coefficient for TF binding
params(29,3) = 0.8; % Kd for TF binding
params(30,1) = 75; % Widom 2011
params(31,1) = 12; % Widom 2011
params(31,2) = 3; % Hill coefficient for TF binding
params(31,3) = 0.8; % Kd for TF binding
params(32,1) = 60; % Widom 2011
params(33,1) = 14.4; % Widom 2011
params(33,2) = 3; % Hill coefficient for TF binding
params(33,3) = 0.8; % Kd for TF binding
params(34,1) = 48; % Widom 2011
params(35,1) = 17.28; % Widom 2011
params(35,2) = 3; % Hill coefficient for TF binding
params(35,3) = 0.8; % Kd for TF binding
params(36,1) = 38.4; % Widom 2011
params(37,1) = 20.736; % Widom 2011
params(37,2) = 3; % Hill coefficient for TF binding
params(37,3) = 0.8; % Kd for TF binding
params(38,1) = 30.72; % Widom 2011
params(39,1) = 24.8832; % Widom 2011
params(39,2) = 3; % Hill coefficient for TF binding
params(39,3) = 0.8; % Kd for TF binding
params(40,1) = 24.576; % Widom 2011
params(41,1) = 29.8598; % Widom 2011
params(41,2) = 3; % Hill coefficient for TF binding
params(41,3) = 0.8; % Kd for TF binding
params(42,1) = 19.6608; % Widom 2011
params(43,1) = 35.8318; % Widom 2011
params(43,2) = 3; % Hill coefficient for TF binding
params(43,3) = 0.8; % Kd for TF binding
params(44,1) = 15.7286; % Widom 2011
params(45,1) = 42.9982; % Widom 2011
params(45,2) = 3; % Hill coefficient for TF binding
params(45,3) = 0.8; % Kd for TF binding
params(46,1) = 12.5829; % Widom 2011
params(47,1) = 51.5978; % Widom 2011
params(47,2) = 3; % Hill coefficient for TF binding
params(47,3) = 0.8; % Kd for TF binding
params(48,1) = 10.0663; % Widom 2011
params(49,1) = 61.9174; % Widom 2011
params(49,2) = 3; % Hill coefficient for TF binding
params(49,3) = 0.8; % Kd for TF binding
params(50,1) = 8.05306; % Widom 2011
params(51,1) = 74.3008; % Widom 2011
params(51,2) = 3; % Hill coefficient for TF binding
params(51,3) = 0.8; % Kd for TF binding
params(52,1) = 6.44245; % Widom 2011
params(53,1) = 89.161; % Widom 2011
params(53,2) = 3; % Hill coefficient for TF binding
params(53,3) = 0.8; % Kd for TF binding
params(54,1) = 5.15396; % Widom 2011
params(55,1) = 106.993; % Widom 2011
params(55,2) = 3; % Hill coefficient for TF binding
params(55,3) = 0.8; % Kd for TF binding
params(56,1) = 4.12317; % Widom 2011
params(57,1) = 0.01; % Assuming constant rate to begin
params(58,1) = 0.01; % Assuming constant rate to begin
params(59,1) = 0.01; % Assuming constant rate to begin
params(60,1) = 0.01; % Assuming constant rate to begin
params(61,1) = 0.01; % Assuming constant rate to begin
params(62,1) = 0.01; % Assuming constant rate to begin
params(63,1) = 0.01; % Assuming constant rate to begin
params(64,1) = 0.01; % Assuming constant rate to begin
params(65,1) = 0.01; % Assuming constant rate to begin
params(66,1) = 0.01; % Assuming constant rate to begin
params(67,1) = 0.01; % Assuming constant rate to begin
params(68,1) = 0.01; % Assuming constant rate to begin
params(69,1) = 0.01; % Assuming constant rate to begin
params(70,1) = 0.01; % Assuming constant rate to begin
params(71,1) = 0.01; % Assuming constant rate to begin


% SPECIES
species.NAMES = {...
'E_0' ...1
'E_1' ...2
'E_2' ...3
'E_3' ...4
'E_4' ...5
'E_5' ...6
'E_6' ...7
'E_7' ...8
'E_8' ...9
'E_9' ...10
'E_10' ...11
'E_11' ...12
'E_12' ...13
'E_13' ...14
'E_14' ...15
'Eh_0' ...16
'Eh_1' ...17
'Eh_2' ...18
'Eh_3' ...19
'Eh_4' ...20
'Eh_5' ...21
'Eh_6' ...22
'Eh_7' ...23
'Eh_8' ...24
'Eh_9' ...25
'Eh_10' ...26
'Eh_11' ...27
'Eh_12' ...28
'Eh_13' ...29
'Eh_14' ...30
};